/* ====================================================
   stats.js — Statistics page logic
   Loads pre-aggregated JSON (generated by
   scripts/build_stats_aggregation.py) and renders 8
   charts + KPI badges.
   ==================================================== */

// ── Network definitions ──────────────────────────────
const NETWORKS = [
  { id: "ethereum", label: "Ethereum",    color: "#3b82f6" },
  { id: "bitcoin",  label: "Bitcoin",     color: "#f59e0b" },
  { id: "bnb",      label: "Binance",     color: "#e3a00d" },
  { id: "uniswap",  label: "Uniswap",     color: "#a855f7" },
  { id: "ripple",   label: "Ripple",      color: "#0ea5e9" },
  { id: "aave",     label: "Aave",        color: "#8b5cf6" },
  { id: "doge",     label: "Dogecoin",    color: "#ca8a04" },
  { id: "hype",     label: "Hyperliquid", color: "#06b6d4" },
  { id: "tron",     label: "Tron",        color: "#ef4444" },
  { id: "cardano",  label: "Cardano",     color: "#0033ad" },
  { id: "stellar",  label: "Stellar",     color: "#000000" },
  { id: "link",     label: "Chainlink",   color: "#2a5ada" },
  { id: "solana",   label: "Solana",      color: "#14f195" },
  { id: "avalanche", label: "Avalanche",  color: "#e84142" },
  { id: "arbitrum",  label: "Arbitrum",   color: "#28a0f0" },
  { id: "polygon",   label: "Polygon",    color: "#8247e5" },
  { id: "near",      label: "NEAR",       color: "#000000" },
  { id: "sui",       label: "Sui",        color: "#4da2ff" },
];

const CONTRIBUTOR_TIERS = [
  { id: "1", label: "Newcomer", range: "1 merged PR", min: 1, max: 1 },
  { id: "2", label: "Explorer", range: "2 merged PRs", min: 2, max: 2 },
  { id: "3-5", label: "Regular", range: "3–5 merged PRs", min: 3, max: 5 },
  { id: "6-10", label: "Builder", range: "6–10 merged PRs", min: 6, max: 10 },
  { id: "11-20", label: "Experienced", range: "11–20 merged PRs", min: 11, max: 20 },
  { id: "21-50", label: "Core", range: "21–50 merged PRs", min: 21, max: 50 },
  { id: "51-100", label: "Veteran", range: "51–100 merged PRs", min: 51, max: 100 },
  { id: "101-500", label: "Elite", range: "101–500 merged PRs", min: 101, max: 500 },
  { id: "501-1000", label: "Legend", range: "501–1000 merged PRs", min: 501, max: 1000 },
  { id: "1000-plus", label: "Icon", range: "More than 1000 merged PRs", min: 1001, max: Infinity },
];

function contributorTier(prCount) {
  return CONTRIBUTOR_TIERS.find((tier) => prCount >= tier.min && prCount <= tier.max) || CONTRIBUTOR_TIERS[0];
}

function t(key, params = {}) {
  return window.pocI18n ? window.pocI18n.t(key, params) : key;
}

// ── Data source ──────────────────────────────────────
const STATS_JSON_URL = "../data/stats-aggregation.json";

const DEFAULT_HIDE_BOTS = true;
const HIDE_BOTS_STORAGE_KEY = "poc.hideBots";
const DEFAULT_HIDE_GHOST = true;
const HIDE_GHOST_STORAGE_KEY = "poc.hideGhost";

function preferredHideBots() {
  try {
    const stored = localStorage.getItem(HIDE_BOTS_STORAGE_KEY);
    return stored === null ? DEFAULT_HIDE_BOTS : stored === "true";
  } catch (error) {
    return DEFAULT_HIDE_BOTS;
  }
}

function saveHideGhostPreference(value) {
  try {
    localStorage.setItem(HIDE_GHOST_STORAGE_KEY, String(value));
  } catch (error) {
  }
}

function preferredHideGhost() {
  try {
    const stored = localStorage.getItem(HIDE_GHOST_STORAGE_KEY);
    return stored === null ? DEFAULT_HIDE_GHOST : stored === "true";
  } catch (error) {
    return DEFAULT_HIDE_GHOST;
  }
}

function isBot(login) {
  return /\[bot\]$/i.test(login) || /bot$/i.test(login);
}

function isGhostUser(login) {
  return login.toLowerCase() === "ghost";
}

// ── Filter hash (memoization support) ─────────────────
function filterHash() {
  const { activeOrgs, range, gran, hideBots, hideGhost } = statsState;
  return `${[...activeOrgs].sort().join(",")}|${range}|${gran}|${hideBots}|${hideGhost}`;
}

// ── State ─────────────────────────────────────────────
const statsState = {
  // aggregated PR counts: Map<orgId, Map<dayKey, number>>
  aggregatedPrs: new Map(),
  // aggregated PR counts excluding bots: Map<orgId, Map<dayKey, number>>
  aggregatedPrsExBots: new Map(),
  // aggregated projects: Map<orgId, Map<dayKey, Map<projectName, number>>>
  projectActivity: new Map(),
  // user data: Map<usuario, { firstSeen: Date, orgs: Set, prCount: number, activeDays: Map, isBot: boolean, isGhost: boolean }>
  userData: new Map(),
  // which orgs are currently visible
  activeOrgs: new Set(NETWORKS.map((n) => n.id)),
  // selected time range in days, or "all"
  range: "all",
  // granularity: "day" | "week" | "month"
  gran: "month",
  hideBots: preferredHideBots(),
  hideGhost: preferredHideGhost(),
  // memoization cache for buildTimeSeries
  _memo: { hash: null, data: null },
};

// ── Chart instances ───────────────────────────────────
let chartMergedPrs = null;
let chartNewContrib = null;
let chartTotalContrib = null;
let chartTotalPrs = null;
let chartContribTiers = null;
let chartNetworkShare = null;
let chartMultiNetwork = null;
let chartDayOfWeek = null;
let chartContributionActivity = null;
let chartContributorRetention = null;

// ── DOM helpers ───────────────────────────────────────
const $ = (id) => document.getElementById(id);

function localizeStatsDom() {
  const textById = {
    loadLabel: "stats.loadingData",
    chartMergedPrsTitle: "stats.mergedPrsTitle",
    chartNewContribTitle: "stats.newContributorsTitle",
    chartTotalContribTitle: "stats.totalContributorsTitle",
    chartTotalPrsTitle: "stats.totalPrsTitle",
    chartContribTiersTitle: "stats.contributorExperienceTitle",
    chartNetworkShareTitle: "stats.developersByNetworkTitle",
    chartMultiNetworkTitle: "stats.ecosystemLoyaltyTitle",
    chartDayOfWeekTitle: "stats.dayOfWeekTitle",
    chartContributionActivityTitle: "stats.contributionActivityTitle",
    chartContributorRetentionTitle: "stats.contributorRetentionTitle",
  };
  Object.entries(textById).forEach(([id, key]) => {
    const el = $(id);
    if (el) el.textContent = t(key);
  });

  const subtitles = [
    ["chartMergedPrsTitle", "stats.mergedPrsSubtitle"],
    ["chartNewContribTitle", "stats.newContributorsSubtitle"],
    ["chartTotalContribTitle", "stats.totalContributorsSubtitle"],
    ["chartTotalPrsTitle", "stats.totalPrsSubtitle"],
    ["chartContribTiersTitle", "stats.contributorExperienceSubtitle"],
    ["chartNetworkShareTitle", "stats.developersByNetworkSubtitle"],
    ["chartMultiNetworkTitle", "stats.ecosystemLoyaltySubtitle"],
    ["chartDayOfWeekTitle", "stats.dayOfWeekSubtitle"],
    ["chartContributionActivityTitle", "stats.contributionActivitySubtitle"],
    ["chartContributorRetentionTitle", "stats.contributorRetentionSubtitle"],
  ];
  subtitles.forEach(([titleId, key]) => {
    const subtitle = $(titleId)?.parentElement?.querySelector(".chart-subtitle");
    if (subtitle) subtitle.textContent = t(key);
  });
}

// ── Legacy CSV parser (kept for potential fallback) ──
// No longer used; data is loaded from pre-aggregated JSON.

// ── Date bucketing ────────────────────────────────────
function parseDate(row) {
  const raw = row.merged_date || row.merged_at || "";
  if (!raw) return null;
  const d = new Date(raw);
  return isNaN(d.getTime()) ? null : d;
}

function bucketKey(date, gran) {
  const y = date.getUTCFullYear();
  const m = String(date.getUTCMonth() + 1).padStart(2, "0");
  const d = String(date.getUTCDate()).padStart(2, "0");
  if (gran === "month") return `${y}-${m}`;
  if (gran === "week") {
    // ISO week start (Monday)
    const t = Date.UTC(y, date.getUTCMonth(), date.getUTCDate());
    const dow = new Date(t).getUTCDay(); // 0=Sun
    const diff = (dow === 0 ? -6 : 1 - dow);
    const monday = new Date(t + diff * 86400000);
    return `${monday.getUTCFullYear()}-${String(monday.getUTCMonth() + 1).padStart(2, "0")}-${String(monday.getUTCDate()).padStart(2, "0")}`;
  }
  return `${y}-${m}-${d}`;
}

function bucketLabel(key, gran) {
  if (gran === "month") {
    const [y, m] = key.split("-");
    const date = new Date(Number(y), Number(m) - 1, 1);
    return date.toLocaleDateString(window.pocI18n?.locale || "en-US", { month: "short", year: "numeric" });
  }
  const [y, m, d] = key.split("-").map(Number);
  const date = new Date(y, m - 1, d || 1);
  return date.toLocaleDateString(window.pocI18n?.locale || "en-US", { month: "short", day: "numeric", year: "numeric" });
}

// ── Range filter ──────────────────────────────────────
function cutoffDate(range) {
  if (range === "all") return null;
  const d = new Date();
  d.setUTCDate(d.getUTCDate() - Number(range));
  d.setUTCHours(0, 0, 0, 0);
  return d;
}

// ── Data processing (memoized, combined passes) ──────
function buildTimeSeries() {
  const hash = filterHash();
  if (statsState._memo.hash === hash) return statsState._memo.data;

  const { aggregatedPrs, aggregatedPrsExBots, userData, activeOrgs, range, gran, hideBots, hideGhost } = statsState;
  const cutoff = cutoffDate(range);
  const effectivePrs = hideBots ? aggregatedPrsExBots : aggregatedPrs;

  // ── Single pass over PR data: orgBuckets + cumulPrs + DoW ──
  const allKeys = new Set();
  const orgBuckets = new Map();
  const totalPrPerBucket = new Map();
  const dowCounts = new Array(7).fill(0);

  effectivePrs.forEach((days, org) => {
    if (!activeOrgs.has(org)) return;
    const buckets = new Map();
    orgBuckets.set(org, buckets);

    days.forEach((count, dayKey) => {
      const [y, m, d] = dayKey.split("-").map(Number);
      const date = new Date(Date.UTC(y, m - 1, d));
      const keep = !cutoff || date >= cutoff;

      if (keep) {
        const key = bucketKey(date, gran);
        allKeys.add(key);
        buckets.set(key, (buckets.get(key) || 0) + count);
        totalPrPerBucket.set(key, (totalPrPerBucket.get(key) || 0) + count);
      }
      dowCounts[date.getUTCDay()] += count;
    });
  });

  const sortedKeys = [...allKeys].sort();
  const labels = sortedKeys.map((k) => bucketLabel(k, gran));

  const mergedPrsDatasets = NETWORKS.filter(n => activeOrgs.has(n.id)).map((net) => {
    const buckets = orgBuckets.get(net.id) || new Map();
    return {
      label: net.label,
      data: sortedKeys.map((k) => buckets.get(k) || 0),
      borderColor: net.color,
      backgroundColor: net.color + "22",
      borderWidth: 2,
      pointRadius: sortedKeys.length > 60 ? 0 : 3,
      pointHoverRadius: 5,
      tension: 0,
      fill: false,
    };
  });

  let runningPrs = 0;
  const cumulPrsData = sortedKeys.map((k) => {
    runningPrs += totalPrPerBucket.get(k) || 0;
    return runningPrs;
  });

  // ── Single pass over user data: filteredUsers + newContribs + tiers + networkShare + loyalty ──
  const filteredUsers = [];
  const activeUsersByBucket = new Map();
  const newContribBuckets = new Map();
  let totalContribBeforeCutoff = 0;
  const tiers = new Map(CONTRIBUTOR_TIERS.map((tier) => [tier.id, 0]));
  const networkCounts = {};
  NETWORKS.filter(n => activeOrgs.has(n.id)).forEach(n => { networkCounts[n.id] = 0; });
  let singleNet = 0, multiNet = 0;

  userData.forEach((data) => {
    if (hideBots && data.isBot) return;
    if (hideGhost && data.isGhost) return;
    const activeUserOrgs = [...data.orgs].filter(o => activeOrgs.has(o));
    if (activeUserOrgs.length === 0) return;
    filteredUsers.push(data);

    // new contributor buckets + cumulative tracking
    const { firstSeen } = data;
    if (cutoff && firstSeen < cutoff) {
      totalContribBeforeCutoff++;
    } else {
      const key = bucketKey(firstSeen, gran);
      if (allKeys.has(key)) {
        newContribBuckets.set(key, (newContribBuckets.get(key) || 0) + 1);
      }
    }

    // contributor tiers
    const count = data.prCount || 0;
    if (count >= 1) {
      const tier = contributorTier(count);
      tiers.set(tier.id, (tiers.get(tier.id) || 0) + 1);
    }

    // network share
    data.orgs.forEach(oid => { if (networkCounts[oid] !== undefined) networkCounts[oid]++; });

    // loyalty
    if (activeUserOrgs.length === 1) singleNet++;
    else if (activeUserOrgs.length > 1) multiNet++;

    activeUserOrgs.forEach((oid) => {
      const days = data.activeDays.get(oid);
      if (!days) return;
      days.forEach((_count, dayKey) => {
        const [y, m, d] = dayKey.split("-").map(Number);
        const date = new Date(Date.UTC(y, m - 1, d));
        if (cutoff && date < cutoff) return;
        const key = bucketKey(date, gran);
        if (!allKeys.has(key)) return;
        if (!activeUsersByBucket.has(key)) activeUsersByBucket.set(key, new Set());
        activeUsersByBucket.get(key).add(data.login);
      });
    });
  });

  const newContribData = sortedKeys.map((k) => newContribBuckets.get(k) || 0);
  let runningContrib = totalContribBeforeCutoff;
  const cumulContribData = sortedKeys.map((k) => {
    runningContrib += newContribBuckets.get(k) || 0;
    return runningContrib;
  });

  const tierData = CONTRIBUTOR_TIERS.map((tier) => ({
    label: t(`tier.${tier.id}`),
    range: t(`tier.range${tier.id}`),
    value: tiers.get(tier.id) || 0,
  }));
  const networkShare = NETWORKS.map(net => ({
    label: net.label,
    value: networkCounts[net.id] || 0,
    color: net.color,
  })).filter(n => n.value > 0);
  const activeContributorData = sortedKeys.map((k) => activeUsersByBucket.get(k)?.size || 0);
  const avgPrsPerActiveContributorData = sortedKeys.map((k, index) => {
    const activeCount = activeContributorData[index] || 0;
    if (activeCount === 0) return 0;
    return Number(((totalPrPerBucket.get(k) || 0) / activeCount).toFixed(2));
  });
  const retainedContributorData = [];
  const retentionRateData = [];
  sortedKeys.forEach((k, index) => {
    if (index === 0) {
      retainedContributorData.push(0);
      retentionRateData.push(0);
      return;
    }
    const previousUsers = activeUsersByBucket.get(sortedKeys[index - 1]) || new Set();
    const currentUsers = activeUsersByBucket.get(k) || new Set();
    let retained = 0;
    previousUsers.forEach((login) => {
      if (currentUsers.has(login)) retained++;
    });
    retainedContributorData.push(retained);
    retentionRateData.push(previousUsers.size ? Number(((retained / previousUsers.size) * 100).toFixed(1)) : 0);
  });

  const result = {
    labels, mergedPrsDatasets, newContribData, cumulContribData, cumulPrsData,
    tierData, networkShare, loyalty: [singleNet, multiNet], dowCounts,
    activeContributorData, avgPrsPerActiveContributorData, retainedContributorData, retentionRateData,
  };

  statsState._memo = { hash, data: result };
  return result;
}

// ── Number formatter ──────────────────────────────────
function fmt(n) {
  return window.pocI18n ? window.pocI18n.formatNumber(n) : new Intl.NumberFormat("en-US").format(n);
}

// ── Chart.js shared defaults ──────────────────────────
function sharedOptions(labels, yLabel) {
  const isDark = document.documentElement.classList.contains("dark");
  const textColor = isDark ? "#94a3b8" : "#687586";
  const gridColor = isDark ? "rgba(255, 255, 255, 0.05)" : "#f0f0f0";

  return {
    responsive: true,
    maintainAspectRatio: true,
    aspectRatio: 1.8,
    animation: false, // Performance: Disable all animations
    normalized: true, // Performance hint
    spanGaps: true,   // Performance hint
    interaction: { mode: "index", intersect: false },
    plugins: {
      legend: {
        position: "top",
        align: "start",
        labels: {
          boxWidth: 12,
          boxHeight: 12,
          borderRadius: 6,
          useBorderRadius: true,
          font: { size: 12, weight: "700" },
          color: textColor,
          padding: 16,
        },
      },
      tooltip: {
        backgroundColor: isDark ? "rgba(30, 41, 59, 0.95)" : "rgba(17, 24, 39, 0.95)",
        titleColor: isDark ? "#f8fafc" : "#f9fafb",
        bodyColor: isDark ? "#94a3b8" : "#d1d5db",
        padding: 12,
        cornerRadius: 10,
        titleFont: { weight: "800" },
        bodyFont: { size: 12 },
        callbacks: {
          label(ctx) {
            return ` ${ctx.dataset.label}: ${fmt(ctx.parsed.y)}`;
          },
        },
      },
    },
    scales: {
      x: {
        grid: { color: gridColor },
        ticks: {
          color: textColor,
          font: { size: 10, weight: "500" },
          maxRotation: 45,
          minRotation: 0,
          autoSkip: true,
          maxTicksLimit: 12,
          callback: function(value) {
            const label = this.getLabelForValue(value);
            // Compact: "Jun 18, 2026" -> "18 Jun"
            // Compact Month: "Jun 2026" -> "Jun '26"
            if (!label.includes(",")) {
               return label.replace(/(\w+) (\d+)/, "$1 '$2"); // Jun 2026 -> Jun '26
            }
            return label.split(",")[0]; // Jun 18, 2026 -> Jun 18
          }
        },
      },
      y: {
        grid: { color: gridColor },
        ticks: {
          color: textColor,
          font: { size: 11 },
          callback: (v) => fmt(v),
        },
        title: {
          display: !!yLabel,
          text: yLabel ?? "",
          color: textColor,
          font: { size: 11, weight: "700" },
        },
      },
    },
  };
}

// ── Chart instance helpers (update in-place or create) ──
function chartUpdate(chartRef, canvasId, config) {
  const canvas = document.getElementById(canvasId);
  if (!canvas) return null;
  if (chartRef && chartRef.canvas && chartRef.canvas.parentNode) {
    // Update existing chart in-place (much cheaper than destroy+create)
    const bothLine = chartRef.config.type === "line" && config.type === "line";
    const bothBar = chartRef.config.type === "bar" && config.type === "bar";
    if (bothLine || bothBar) {
      chartRef.data.labels = config.data.labels;
      chartRef.data.datasets = config.data.datasets;
      // Deep replace options so nested theme colors take effect
      chartRef.options = Chart.helpers.merge({}, config.options);
      chartRef.update("none");
      return chartRef;
    }
    chartRef.destroy();
  }
  return new Chart(canvas.getContext("2d"), config);
}

function renderChart1(data) {
  const { labels, mergedPrsDatasets } = data;
  chartMergedPrs = chartUpdate(chartMergedPrs, "chartMergedPrs", {
    type: "line",
    data: { labels, datasets: mergedPrsDatasets },
    options: {
      ...sharedOptions(labels, t("stats.prsMerged")),
      plugins: { ...sharedOptions(labels, t("stats.prsMerged")).plugins, legend: { display: false } },
    },
  });
}

function renderChart2(data) {
  const { labels, newContribData } = data;
  chartNewContrib = chartUpdate(chartNewContrib, "chartNewContrib", {
    type: "bar",
    data: {
      labels,
      datasets: [{
        label: t("stats.newContributors"), data: newContribData,
        backgroundColor: "rgba(79, 70, 229, 0.72)", borderRadius: 4,
      }],
    },
    options: {
      ...sharedOptions(labels, t("stats.newContributors")),
      plugins: {
        ...sharedOptions(labels).plugins, legend: { display: false },
        tooltip: { ...sharedOptions(labels).plugins.tooltip, callbacks: { label: (ctx) => ` ${fmt(ctx.parsed.y)} ${t("stats.newContributors").toLowerCase()}` } },
      },
    },
  });
}

function renderChart3(data) {
  const { labels, cumulContribData } = data;
  chartTotalContrib = chartUpdate(chartTotalContrib, "chartTotalContrib", {
    type: "line",
    data: {
      labels,
      datasets: [{
        label: t("stats.totalContributors"), data: cumulContribData,
        borderColor: "#10b981", backgroundColor: "rgba(16, 185, 129, 0.12)",
        borderWidth: 2, tension: 0.1, fill: true,
        pointRadius: labels.length > 60 ? 0 : 3,
      }],
    },
    options: {
      ...sharedOptions(labels, t("common.contributors")),
      plugins: {
        ...sharedOptions(labels).plugins, legend: { display: false },
        tooltip: { ...sharedOptions(labels).plugins.tooltip, callbacks: { label: (ctx) => ` ${fmt(ctx.parsed.y)} ${t("common.contributors").toLowerCase()}` } },
      },
    },
  });
}

function renderChart4(data) {
  const { labels, cumulPrsData } = data;
  chartTotalPrs = chartUpdate(chartTotalPrs, "chartTotalPrs", {
    type: "line",
    data: {
      labels,
      datasets: [{
        label: t("stats.totalPrsTitle"), data: cumulPrsData,
        borderColor: "#f59e0b", backgroundColor: "rgba(245, 158, 11, 0.1)",
        borderWidth: 2, tension: 0.1, fill: true,
        pointRadius: labels.length > 60 ? 0 : 3,
      }],
    },
    options: {
      ...sharedOptions(labels, t("stats.mergedPrs")),
      plugins: {
        ...sharedOptions(labels).plugins, legend: { display: false },
        tooltip: { ...sharedOptions(labels).plugins.tooltip, callbacks: { label: (ctx) => ` ${fmt(ctx.parsed.y)} ${t("common.prs")}` } },
      },
    },
  });
}

function renderChart5(data) {
  const { tierData } = data;
  chartContribTiers = chartUpdate(chartContribTiers, "chartContribTiers", {
    type: "bar",
    data: {
      labels: tierData.map(t => t.label),
      datasets: [{
    label: t("stats.developers"), data: tierData.map(t => t.value),
        backgroundColor: ["#94a3b8", "#6366f1", "#4f46e5", "#3730a3"],
        borderRadius: 4,
      }],
    },
    options: {
      ...sharedOptions([], t("stats.developers")), aspectRatio: 1.5,
      plugins: {
        ...sharedOptions().plugins,
        legend: { display: false },
        tooltip: {
          ...sharedOptions().plugins.tooltip,
          callbacks: {
            label(ctx) {
              const tier = tierData[ctx.dataIndex];
              return ` ${fmt(ctx.parsed.y)} ${t("stats.developers").toLowerCase()} (${tier.range})`;
            },
          },
        },
      },
    },
  });
}

function renderChart6(data) {
  const { networkShare } = data;
  chartNetworkShare = chartUpdate(chartNetworkShare, "chartNetworkShare", {
    type: "doughnut",
    data: {
      labels: networkShare.map(n => n.label),
      datasets: [{ data: networkShare.map(n => n.value), backgroundColor: networkShare.map(n => n.color), borderWidth: 0 }],
    },
    options: {
      aspectRatio: 1.5,
      plugins: {
        legend: { position: 'right', labels: { boxWidth: 12, font: { size: 11 } } },
        tooltip: { callbacks: { label(ctx) { return ` ${ctx.label || ""}: ${fmt(ctx.parsed || 0)} ${t("stats.developers").toLowerCase()}`; } } },
      },
    },
  });
}

function renderChart7(data) {
  const { loyalty } = data;
  chartMultiNetwork = chartUpdate(chartMultiNetwork, "chartMultiNetwork", {
    type: "pie",
    data: {
      labels: [t("stats.singleNetwork"), t("stats.multiNetwork")],
      datasets: [{ data: loyalty, backgroundColor: ["#4f46e5", "#10b981"], borderWidth: 0 }],
    },
    options: {
      aspectRatio: 1.5,
      plugins: { legend: { position: 'right', labels: { boxWidth: 12, font: { size: 11 } } } },
    },
  });
}

function renderChart8(data) {
  const { dowCounts } = data;
  const dowLabels = [
    t("stats.daySun"), t("stats.dayMon"), t("stats.dayTue"), t("stats.dayWed"),
    t("stats.dayThu"), t("stats.dayFri"), t("stats.daySat"),
  ];
  chartDayOfWeek = chartUpdate(chartDayOfWeek, "chartDayOfWeek", {
    type: "bar",
    data: {
      labels: dowLabels,
      datasets: [{ label: t("stats.totalActivity"), data: dowCounts, backgroundColor: "rgba(79, 70, 229, 0.7)", borderRadius: 4 }],
    },
    options: {
      ...sharedOptions(dowLabels, t("stats.totalPrsAxis")), aspectRatio: 1.5,
      plugins: { ...sharedOptions().plugins, legend: { display: false } },
    },
  });
}

// ── Render charts (progressive) ──────────────────────
function renderChart9(data) {
  const { labels, activeContributorData, avgPrsPerActiveContributorData } = data;
  const options = sharedOptions(labels, t("stats.activeContributors"));
  options.scales.y1 = {
    position: "right",
    grid: { drawOnChartArea: false },
    ticks: {
      color: options.scales.y.ticks.color,
      font: { size: 11 },
      callback: (v) => Number(v).toFixed(1),
    },
    title: {
      display: true,
      text: t("stats.avgPrs"),
      color: options.scales.y.title.color,
      font: { size: 11, weight: "700" },
    },
  };
  options.plugins.legend = { display: true, position: "top", align: "start" };
  options.plugins.tooltip.callbacks = {
    label(ctx) {
      if (ctx.dataset.yAxisID === "y1") return ` ${ctx.dataset.label}: ${Number(ctx.parsed.y).toFixed(2)}`;
      return ` ${ctx.dataset.label}: ${fmt(ctx.parsed.y)}`;
    },
  };

  chartContributionActivity = chartUpdate(chartContributionActivity, "chartContributionActivity", {
    type: "bar",
    data: {
      labels,
      datasets: [
        {
          label: t("stats.activeContributors"),
          data: activeContributorData,
          backgroundColor: "rgba(14, 165, 233, 0.72)",
          borderRadius: 4,
          yAxisID: "y",
        },
        {
          type: "line",
          label: t("stats.avgPrsPerActiveContributor"),
          data: avgPrsPerActiveContributorData,
          borderColor: "#f59e0b",
          backgroundColor: "rgba(245, 158, 11, 0.1)",
          borderWidth: 2,
          pointRadius: labels.length > 60 ? 0 : 3,
          tension: 0.1,
          yAxisID: "y1",
        },
      ],
    },
    options,
  });
}

function renderChart10(data) {
  const { labels, retainedContributorData, retentionRateData } = data;
  const options = sharedOptions(labels, t("stats.retainedContributors"));
  options.scales.y1 = {
    position: "right",
    min: 0,
    max: 100,
    grid: { drawOnChartArea: false },
    ticks: {
      color: options.scales.y.ticks.color,
      font: { size: 11 },
      callback: (v) => `${v}%`,
    },
    title: {
      display: true,
      text: t("stats.retention"),
      color: options.scales.y.title.color,
      font: { size: 11, weight: "700" },
    },
  };
  options.plugins.legend = { display: true, position: "top", align: "start" };
  options.plugins.tooltip.callbacks = {
    label(ctx) {
      if (ctx.dataset.yAxisID === "y1") return ` ${ctx.dataset.label}: ${Number(ctx.parsed.y).toFixed(1)}%`;
      return ` ${ctx.dataset.label}: ${fmt(ctx.parsed.y)}`;
    },
  };

  chartContributorRetention = chartUpdate(chartContributorRetention, "chartContributorRetention", {
    type: "bar",
    data: {
      labels,
      datasets: [
        {
          label: t("stats.retainedContributors"),
          data: retainedContributorData,
          backgroundColor: "rgba(16, 185, 129, 0.72)",
          borderRadius: 4,
          yAxisID: "y",
        },
        {
          type: "line",
          label: t("stats.retentionRate"),
          data: retentionRateData,
          borderColor: "#4f46e5",
          backgroundColor: "rgba(79, 70, 229, 0.1)",
          borderWidth: 2,
          pointRadius: labels.length > 60 ? 0 : 3,
          tension: 0.1,
          yAxisID: "y1",
        },
      ],
    },
    options,
  });
}

function renderCharts() {
  const data = buildTimeSeries();

  // KPI badges (synchronous, cheap)
  const totalMergedPrs = data.mergedPrsDatasets.reduce((sum, ds) => sum + ds.data.reduce((s, v) => s + v, 0), 0);
  $("badgeMergedPrs").textContent = `${fmt(totalMergedPrs)} ${t("common.prs")}`;
  $("badgeNewContrib").textContent = t("stats.newBadge", { count: fmt(data.newContribData.reduce((s, v) => s + v, 0)) });
  $("badgeTotalContrib").textContent = t("stats.totalBadge", { count: fmt(data.cumulContribData.at(-1) ?? 0) });
  $("badgeTotalPrs").textContent = t("stats.cumulativeBadge", { count: fmt(data.cumulPrsData.at(-1) ?? 0) });
  $("badgeContributionActivity").textContent = t("stats.peakBadge", { count: fmt(Math.max(...data.activeContributorData, 0)) });
  const latestRetention = [...data.retentionRateData].reverse().find((value) => value > 0) || 0;
  $("badgeContributorRetention").textContent = t("stats.latestBadge", { value: latestRetention.toFixed(1) });

  // Chart 1 (most important — render immediately)
  renderChart1(data);

  // Charts 2-4 (schedule as a batch)
  setTimeout(() => {
    renderChart2(data);
    renderChart3(data);
    renderChart4(data);
  }, 0);

  // Charts 5-8 (second batch)
  setTimeout(() => {
    renderChart5(data);
    renderChart6(data);
    renderChart7(data);
    renderChart8(data);
  }, 50);

  setTimeout(() => {
    renderChart9(data);
    renderChart10(data);
  }, 100);
}

// ── Network toggle UI ─────────────────────────────────
function resetActiveOrgs() {
  statsState.activeOrgs = new Set(NETWORKS.map((n) => n.id));
}

function bindNetworkToggles() {
  const wrap = $("networkToggles");
  wrap.addEventListener("click", (e) => {
    const btn = e.target.closest("[data-org]");
    if (!btn) return;
    const org = btn.dataset.org;
    if (statsState.activeOrgs.has(org)) {
      statsState.activeOrgs.delete(org);
      if (statsState.activeOrgs.size === 0) resetActiveOrgs();
    } else {
      statsState.activeOrgs.add(org);
    }
    renderNetworkToggles();
    renderCharts();
  });
}

function renderNetworkToggles() {
  const wrap = $("networkToggles");
  wrap.innerHTML = NETWORKS.map((net) => {
    const active = statsState.activeOrgs.has(net.id);
    return `
      <button
        class="net-toggle ${active ? "active" : ""}"
        data-org="${net.id}"
        type="button"
        style="color: ${net.color};"
        aria-pressed="${active}"
      >
        <span class="net-dot" style="background:${net.color};"></span>
        ${net.label}
      </button>`;
  }).join("");
}

// ── Time range buttons ────────────────────────────────
function bindTimeButtons() {
  document.querySelectorAll(".time-btn").forEach((btn) => {
    btn.addEventListener("click", () => {
      document.querySelectorAll(".time-btn").forEach((b) => b.classList.remove("active"));
      btn.classList.add("active");
      statsState.range = btn.dataset.range;
      renderCharts();
    });
  });
}

function bindGranButtons() {
  document.querySelectorAll(".gran-btn").forEach((btn) => {
    btn.addEventListener("click", () => {
      document.querySelectorAll(".gran-btn").forEach((b) => b.classList.remove("active"));
      btn.classList.add("active");
      statsState.gran = btn.dataset.gran;
      renderCharts();
    });
  });
}

// ── Hide bots / ghost toggles ───────────────────────────
function bindHideBotsToggle() {
  const cb = $("hideBotsStats");
  if (!cb) return;
  cb.addEventListener("change", () => {
    statsState.hideBots = cb.checked;
    try {
      localStorage.setItem(HIDE_BOTS_STORAGE_KEY, String(cb.checked));
    } catch (_) { /* ignore */ }
    renderCharts();
  });
}

function bindHideGhostToggle() {
  const cb = $("hideGhostStats");
  if (!cb) return;
  cb.addEventListener("change", () => {
    statsState.hideGhost = cb.checked;
    saveHideGhostPreference(statsState.hideGhost);
    renderCharts();
  });
}

// ── Data loading (from pre-aggregated JSON) ──────────
async function loadAll() {
  if (window.pocI18n) {
    await window.pocI18n.ready;
  }
  localizeStatsDom();
  const loadState = $("statsLoadState");
  const chartsGrid = $("chartsGrid");
  const loadLabel = $("loadLabel");
  const statusEl = $("dataStatus");

  loadState.removeAttribute("hidden");
  chartsGrid.setAttribute("hidden", "");

  let payload;
  try {
    const res = await fetch(STATS_JSON_URL, { cache: "no-store" });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    payload = await res.json();
  } catch (err) {
    loadLabel.textContent = "";
    if (statusEl) {
      statusEl.innerHTML = `<span class="error">${t("stats.loadFailed", { message: err.message })}</span>`;
    }
    return;
  }

  // Convert JSON objects to Maps
  const { aggregated_prs, aggregated_prs_ex_bots, users } = payload;
  for (const [org, days] of Object.entries(aggregated_prs)) {
    const m = new Map();
    for (const [k, v] of Object.entries(days)) m.set(k, v);
    statsState.aggregatedPrs.set(org, m);
  }
  for (const [org, days] of Object.entries(aggregated_prs_ex_bots)) {
    const m = new Map();
    for (const [k, v] of Object.entries(days)) m.set(k, v);
    statsState.aggregatedPrsExBots.set(org, m);
  }
  for (const u of users) {
    const activeDays = new Map();
    if (u.active_days && typeof u.active_days === "object") {
      for (const [org, days] of Object.entries(u.active_days)) {
        activeDays.set(org, new Map(Object.entries(days)));
      }
    } else {
      for (const org of u.orgs || []) {
        activeDays.set(org, new Map([[u.first_seen, u.pr_count || 1]]));
      }
    }
    statsState.userData.set(u.login, {
      login: u.login,
      firstSeen: new Date(u.first_seen),
      orgs: new Set(u.orgs),
      prCount: u.pr_count,
      activeDays,
      isBot: u.is_bot,
      isGhost: u.is_ghost,
    });
  }

  loadLabel.textContent = t("stats.loadSummary", { contributors: fmt(payload.user_count), prs: fmt(payload.total_rows) });
  loadState.setAttribute("hidden", "");
  chartsGrid.removeAttribute("hidden");

  renderNetworkToggles();
  bindNetworkToggles();
  bindTimeButtons();
  bindGranButtons();
  bindHideBotsToggle();
  bindHideGhostToggle();

  const hb = $("hideBotsStats");
  if (hb) hb.checked = statsState.hideBots;
  const hg = $("hideGhostStats");
  if (hg) hg.checked = statsState.hideGhost;

  renderCharts();

  const observer = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
      if (mutation.attributeName === "class") {
        statsState._memo.hash = null;
        renderCharts();
      }
    });
  });
  observer.observe(document.documentElement, { attributes: true });
}

loadAll().catch((err) => {
  const statusEl = $("dataStatus");
  if (statusEl) {
    statusEl.innerHTML = `<span class="error">${err.message || String(err)}</span>`;
  }
  console.error(err);
});
