/* ====================================================
   stats.js — Statistics page logic
   Loads pre-aggregated JSON (generated by
   scripts/build_stats_aggregation.py) and renders 8
   charts + KPI badges.
   ==================================================== */

// ── Network definitions ──────────────────────────────
const NETWORKS = [
  { id: "ethereum", label: "Ethereum",    color: "#3b82f6" },
  { id: "bitcoin",  label: "Bitcoin",     color: "#f59e0b" },
  { id: "bnb",      label: "Binance",     color: "#e3a00d" },
  { id: "uniswap",  label: "Uniswap",     color: "#a855f7" },
  { id: "ripple",   label: "Ripple",      color: "#0ea5e9" },
  { id: "aave",     label: "Aave",        color: "#8b5cf6" },
  { id: "doge",     label: "Dogecoin",    color: "#ca8a04" },
  { id: "hype",     label: "Hyperliquid", color: "#06b6d4" },
  { id: "tron",     label: "Tron",        color: "#ef4444" },
  { id: "cardano",  label: "Cardano",     color: "#0033ad" },
  { id: "stellar",  label: "Stellar",     color: "#000000" },
  { id: "link",     label: "Chainlink",   color: "#2a5ada" },
  { id: "solana",   label: "Solana",      color: "#14f195" },
];

// ── Data source ──────────────────────────────────────
const STATS_JSON_URL = "../data/stats-aggregation.json";

const DEFAULT_HIDE_BOTS = true;
const HIDE_BOTS_STORAGE_KEY = "poc.hideBots";
const DEFAULT_HIDE_GHOST = true;
const HIDE_GHOST_STORAGE_KEY = "poc.hideGhost";

function preferredHideBots() {
  try {
    const stored = localStorage.getItem(HIDE_BOTS_STORAGE_KEY);
    return stored === null ? DEFAULT_HIDE_BOTS : stored === "true";
  } catch (error) {
    return DEFAULT_HIDE_BOTS;
  }
}

function saveHideGhostPreference(value) {
  try {
    localStorage.setItem(HIDE_GHOST_STORAGE_KEY, String(value));
  } catch (error) {
  }
}

function preferredHideGhost() {
  try {
    const stored = localStorage.getItem(HIDE_GHOST_STORAGE_KEY);
    return stored === null ? DEFAULT_HIDE_GHOST : stored === "true";
  } catch (error) {
    return DEFAULT_HIDE_GHOST;
  }
}

function isBot(login) {
  return /\[bot\]$/i.test(login) || /bot$/i.test(login);
}

function isGhostUser(login) {
  return login.toLowerCase() === "ghost";
}

// ── Filter hash (memoization support) ─────────────────
function filterHash() {
  const { activeOrgs, range, gran, hideBots, hideGhost } = statsState;
  return `${[...activeOrgs].sort().join(",")}|${range}|${gran}|${hideBots}|${hideGhost}`;
}

// ── State ─────────────────────────────────────────────
const statsState = {
  // aggregated PR counts: Map<orgId, Map<dayKey, number>>
  aggregatedPrs: new Map(),
  // aggregated PR counts excluding bots: Map<orgId, Map<dayKey, number>>
  aggregatedPrsExBots: new Map(),
  // aggregated projects: Map<orgId, Map<dayKey, Map<projectName, number>>>
  projectActivity: new Map(),
  // user data: Map<usuario, { firstSeen: Date, orgs: Set, prCount: number, isBot: boolean, isGhost: boolean }>
  userData: new Map(),
  // which orgs are currently visible
  activeOrgs: new Set(NETWORKS.map((n) => n.id)),
  // selected time range in days, or "all"
  range: "all",
  // granularity: "day" | "week" | "month"
  gran: "month",
  hideBots: preferredHideBots(),
  hideGhost: preferredHideGhost(),
  // memoization cache for buildTimeSeries
  _memo: { hash: null, data: null },
};

// ── Chart instances ───────────────────────────────────
let chartMergedPrs = null;
let chartNewContrib = null;
let chartTotalContrib = null;
let chartTotalPrs = null;
let chartContribTiers = null;
let chartNetworkShare = null;
let chartMultiNetwork = null;
let chartDayOfWeek = null;

// ── DOM helpers ───────────────────────────────────────
const $ = (id) => document.getElementById(id);

// ── Legacy CSV parser (kept for potential fallback) ──
// No longer used; data is loaded from pre-aggregated JSON.

// ── Date bucketing ────────────────────────────────────
function parseDate(row) {
  const raw = row.merged_date || row.merged_at || "";
  if (!raw) return null;
  const d = new Date(raw);
  return isNaN(d.getTime()) ? null : d;
}

function bucketKey(date, gran) {
  const y = date.getUTCFullYear();
  const m = String(date.getUTCMonth() + 1).padStart(2, "0");
  const d = String(date.getUTCDate()).padStart(2, "0");
  if (gran === "month") return `${y}-${m}`;
  if (gran === "week") {
    // ISO week start (Monday)
    const t = Date.UTC(y, date.getUTCMonth(), date.getUTCDate());
    const dow = new Date(t).getUTCDay(); // 0=Sun
    const diff = (dow === 0 ? -6 : 1 - dow);
    const monday = new Date(t + diff * 86400000);
    return `${monday.getUTCFullYear()}-${String(monday.getUTCMonth() + 1).padStart(2, "0")}-${String(monday.getUTCDate()).padStart(2, "0")}`;
  }
  return `${y}-${m}-${d}`;
}

function bucketLabel(key, gran) {
  if (gran === "month") {
    const [y, m] = key.split("-");
    const date = new Date(Number(y), Number(m) - 1, 1);
    return date.toLocaleDateString("en-US", { month: "short", year: "numeric" });
  }
  const [y, m, d] = key.split("-").map(Number);
  const date = new Date(y, m - 1, d || 1);
  return date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

// ── Range filter ──────────────────────────────────────
function cutoffDate(range) {
  if (range === "all") return null;
  const d = new Date();
  d.setUTCDate(d.getUTCDate() - Number(range));
  d.setUTCHours(0, 0, 0, 0);
  return d;
}

// ── Data processing (memoized, combined passes) ──────
function buildTimeSeries() {
  const hash = filterHash();
  if (statsState._memo.hash === hash) return statsState._memo.data;

  const { aggregatedPrs, aggregatedPrsExBots, userData, activeOrgs, range, gran, hideBots, hideGhost } = statsState;
  const cutoff = cutoffDate(range);
  const effectivePrs = hideBots ? aggregatedPrsExBots : aggregatedPrs;

  // ── Single pass over PR data: orgBuckets + cumulPrs + DoW ──
  const allKeys = new Set();
  const orgBuckets = new Map();
  const totalPrPerBucket = new Map();
  const dowCounts = new Array(7).fill(0);

  effectivePrs.forEach((days, org) => {
    if (!activeOrgs.has(org)) return;
    const buckets = new Map();
    orgBuckets.set(org, buckets);

    days.forEach((count, dayKey) => {
      const [y, m, d] = dayKey.split("-").map(Number);
      const date = new Date(Date.UTC(y, m - 1, d));
      const keep = !cutoff || date >= cutoff;

      if (keep) {
        const key = bucketKey(date, gran);
        allKeys.add(key);
        buckets.set(key, (buckets.get(key) || 0) + count);
        totalPrPerBucket.set(key, (totalPrPerBucket.get(key) || 0) + count);
      }
      dowCounts[date.getUTCDay()] += count;
    });
  });

  const sortedKeys = [...allKeys].sort();
  const labels = sortedKeys.map((k) => bucketLabel(k, gran));

  const mergedPrsDatasets = NETWORKS.filter(n => activeOrgs.has(n.id)).map((net) => {
    const buckets = orgBuckets.get(net.id) || new Map();
    return {
      label: net.label,
      data: sortedKeys.map((k) => buckets.get(k) || 0),
      borderColor: net.color,
      backgroundColor: net.color + "22",
      borderWidth: 2,
      pointRadius: sortedKeys.length > 60 ? 0 : 3,
      pointHoverRadius: 5,
      tension: 0,
      fill: false,
    };
  });

  let runningPrs = 0;
  const cumulPrsData = sortedKeys.map((k) => {
    runningPrs += totalPrPerBucket.get(k) || 0;
    return runningPrs;
  });

  // ── Single pass over user data: filteredUsers + newContribs + tiers + networkShare + loyalty ──
  const filteredUsers = [];
  const newContribBuckets = new Map();
  let totalContribBeforeCutoff = 0;
  const tiers = { "1 PR": 0, "2-5 PRs": 0, "6-20 PRs": 0, "21+ PRs": 0 };
  const networkCounts = {};
  NETWORKS.filter(n => activeOrgs.has(n.id)).forEach(n => { networkCounts[n.id] = 0; });
  let singleNet = 0, multiNet = 0;

  userData.forEach((data) => {
    if (hideBots && data.isBot) return;
    if (hideGhost && data.isGhost) return;
    const activeUserOrgs = [...data.orgs].filter(o => activeOrgs.has(o));
    if (activeUserOrgs.length === 0) return;
    filteredUsers.push(data);

    // new contributor buckets + cumulative tracking
    const { firstSeen } = data;
    if (cutoff && firstSeen < cutoff) {
      totalContribBeforeCutoff++;
    } else {
      const key = bucketKey(firstSeen, gran);
      if (allKeys.has(key)) {
        newContribBuckets.set(key, (newContribBuckets.get(key) || 0) + 1);
      }
    }

    // contributor tiers
    const count = data.prCount || 0;
    if (count >= 21) tiers["21+ PRs"]++;
    else if (count >= 6) tiers["6-20 PRs"]++;
    else if (count >= 2) tiers["2-5 PRs"]++;
    else if (count >= 1) tiers["1 PR"]++;

    // network share
    data.orgs.forEach(oid => { if (networkCounts[oid] !== undefined) networkCounts[oid]++; });

    // loyalty
    if (activeUserOrgs.length === 1) singleNet++;
    else if (activeUserOrgs.length > 1) multiNet++;
  });

  const newContribData = sortedKeys.map((k) => newContribBuckets.get(k) || 0);
  let runningContrib = totalContribBeforeCutoff;
  const cumulContribData = sortedKeys.map((k) => {
    runningContrib += newContribBuckets.get(k) || 0;
    return runningContrib;
  });

  const tierData = Object.keys(tiers).map(k => ({ label: k, value: tiers[k] }));
  const networkShare = NETWORKS.map(net => ({
    label: net.label,
    value: networkCounts[net.id] || 0,
    color: net.color,
  })).filter(n => n.value > 0);

  const result = {
    labels, mergedPrsDatasets, newContribData, cumulContribData, cumulPrsData,
    tierData, networkShare, loyalty: [singleNet, multiNet], dowCounts,
  };

  statsState._memo = { hash, data: result };
  return result;
}

// ── Number formatter ──────────────────────────────────
function fmt(n) {
  return new Intl.NumberFormat("en-US").format(n);
}

// ── Chart.js shared defaults ──────────────────────────
function sharedOptions(labels, yLabel) {
  const isDark = document.documentElement.classList.contains("dark");
  const textColor = isDark ? "#94a3b8" : "#687586";
  const gridColor = isDark ? "rgba(255, 255, 255, 0.05)" : "#f0f0f0";

  return {
    responsive: true,
    maintainAspectRatio: true,
    aspectRatio: 1.8,
    animation: false, // Performance: Disable all animations
    normalized: true, // Performance hint
    spanGaps: true,   // Performance hint
    interaction: { mode: "index", intersect: false },
    plugins: {
      legend: {
        position: "top",
        align: "start",
        labels: {
          boxWidth: 12,
          boxHeight: 12,
          borderRadius: 6,
          useBorderRadius: true,
          font: { size: 12, weight: "700" },
          color: textColor,
          padding: 16,
        },
      },
      tooltip: {
        backgroundColor: isDark ? "rgba(30, 41, 59, 0.95)" : "rgba(17, 24, 39, 0.95)",
        titleColor: isDark ? "#f8fafc" : "#f9fafb",
        bodyColor: isDark ? "#94a3b8" : "#d1d5db",
        padding: 12,
        cornerRadius: 10,
        titleFont: { weight: "800" },
        bodyFont: { size: 12 },
        callbacks: {
          label(ctx) {
            return ` ${ctx.dataset.label}: ${fmt(ctx.parsed.y)}`;
          },
        },
      },
    },
    scales: {
      x: {
        grid: { color: gridColor },
        ticks: {
          color: textColor,
          font: { size: 10, weight: "500" },
          maxRotation: 45,
          minRotation: 0,
          autoSkip: true,
          maxTicksLimit: 12,
          callback: function(value) {
            const label = this.getLabelForValue(value);
            // Compact: "Jun 18, 2026" -> "18 Jun"
            // Compact Month: "Jun 2026" -> "Jun '26"
            if (!label.includes(",")) {
               return label.replace(/(\w+) (\d+)/, "$1 '$2"); // Jun 2026 -> Jun '26
            }
            return label.split(",")[0]; // Jun 18, 2026 -> Jun 18
          }
        },
      },
      y: {
        grid: { color: gridColor },
        ticks: {
          color: textColor,
          font: { size: 11 },
          callback: (v) => fmt(v),
        },
        title: {
          display: !!yLabel,
          text: yLabel ?? "",
          color: textColor,
          font: { size: 11, weight: "700" },
        },
      },
    },
  };
}

// ── Chart instance helpers (update in-place or create) ──
function chartUpdate(chartRef, canvasId, config) {
  const canvas = document.getElementById(canvasId);
  if (!canvas) return null;
  if (chartRef && chartRef.canvas && chartRef.canvas.parentNode) {
    // Update existing chart in-place (much cheaper than destroy+create)
    const bothLine = chartRef.config.type === "line" && config.type === "line";
    const bothBar = chartRef.config.type === "bar" && config.type === "bar";
    if (bothLine || bothBar) {
      chartRef.data.labels = config.data.labels;
      chartRef.data.datasets = config.data.datasets;
      // Deep replace options so nested theme colors take effect
      chartRef.options = Chart.helpers.merge({}, config.options);
      chartRef.update("none");
      return chartRef;
    }
    chartRef.destroy();
  }
  return new Chart(canvas.getContext("2d"), config);
}

function renderChart1(data) {
  const { labels, mergedPrsDatasets } = data;
  chartMergedPrs = chartUpdate(chartMergedPrs, "chartMergedPrs", {
    type: "line",
    data: { labels, datasets: mergedPrsDatasets },
    options: {
      ...sharedOptions(labels, "PRs merged"),
      plugins: { ...sharedOptions(labels, "PRs merged").plugins, legend: { display: false } },
    },
  });
}

function renderChart2(data) {
  const { labels, newContribData } = data;
  chartNewContrib = chartUpdate(chartNewContrib, "chartNewContrib", {
    type: "bar",
    data: {
      labels,
      datasets: [{
        label: "New contributors", data: newContribData,
        backgroundColor: "rgba(79, 70, 229, 0.72)", borderRadius: 4,
      }],
    },
    options: {
      ...sharedOptions(labels, "New contributors"),
      plugins: {
        ...sharedOptions(labels).plugins, legend: { display: false },
        tooltip: { ...sharedOptions(labels).plugins.tooltip, callbacks: { label: (ctx) => ` ${fmt(ctx.parsed.y)} new contributors` } },
      },
    },
  });
}

function renderChart3(data) {
  const { labels, cumulContribData } = data;
  chartTotalContrib = chartUpdate(chartTotalContrib, "chartTotalContrib", {
    type: "line",
    data: {
      labels,
      datasets: [{
        label: "Total contributors", data: cumulContribData,
        borderColor: "#10b981", backgroundColor: "rgba(16, 185, 129, 0.12)",
        borderWidth: 2, tension: 0.1, fill: true,
        pointRadius: labels.length > 60 ? 0 : 3,
      }],
    },
    options: {
      ...sharedOptions(labels, "Contributors"),
      plugins: {
        ...sharedOptions(labels).plugins, legend: { display: false },
        tooltip: { ...sharedOptions(labels).plugins.tooltip, callbacks: { label: (ctx) => ` ${fmt(ctx.parsed.y)} contributors` } },
      },
    },
  });
}

function renderChart4(data) {
  const { labels, cumulPrsData } = data;
  chartTotalPrs = chartUpdate(chartTotalPrs, "chartTotalPrs", {
    type: "line",
    data: {
      labels,
      datasets: [{
        label: "Total merged PRs", data: cumulPrsData,
        borderColor: "#f59e0b", backgroundColor: "rgba(245, 158, 11, 0.1)",
        borderWidth: 2, tension: 0.1, fill: true,
        pointRadius: labels.length > 60 ? 0 : 3,
      }],
    },
    options: {
      ...sharedOptions(labels, "Merged PRs"),
      plugins: {
        ...sharedOptions(labels).plugins, legend: { display: false },
        tooltip: { ...sharedOptions(labels).plugins.tooltip, callbacks: { label: (ctx) => ` ${fmt(ctx.parsed.y)} total PRs` } },
      },
    },
  });
}

function renderChart5(data) {
  const { tierData } = data;
  chartContribTiers = chartUpdate(chartContribTiers, "chartContribTiers", {
    type: "bar",
    data: {
      labels: tierData.map(t => t.label),
      datasets: [{
        label: "Developers", data: tierData.map(t => t.value),
        backgroundColor: ["#94a3b8", "#6366f1", "#4f46e5", "#3730a3"],
        borderRadius: 4,
      }],
    },
    options: {
      ...sharedOptions([], "Developers"), aspectRatio: 1.5,
      plugins: { ...sharedOptions().plugins, legend: { display: false } },
    },
  });
}

function renderChart6(data) {
  const { networkShare } = data;
  chartNetworkShare = chartUpdate(chartNetworkShare, "chartNetworkShare", {
    type: "doughnut",
    data: {
      labels: networkShare.map(n => n.label),
      datasets: [{ data: networkShare.map(n => n.value), backgroundColor: networkShare.map(n => n.color), borderWidth: 0 }],
    },
    options: {
      aspectRatio: 1.5,
      plugins: {
        legend: { position: 'right', labels: { boxWidth: 12, font: { size: 11 } } },
        tooltip: { callbacks: { label(ctx) { return ` ${ctx.label || ""}: ${fmt(ctx.parsed || 0)} developers`; } } },
      },
    },
  });
}

function renderChart7(data) {
  const { loyalty } = data;
  chartMultiNetwork = chartUpdate(chartMultiNetwork, "chartMultiNetwork", {
    type: "pie",
    data: {
      labels: ["Single Network", "Multi-network"],
      datasets: [{ data: loyalty, backgroundColor: ["#4f46e5", "#10b981"], borderWidth: 0 }],
    },
    options: {
      aspectRatio: 1.5,
      plugins: { legend: { position: 'right', labels: { boxWidth: 12, font: { size: 11 } } } },
    },
  });
}

function renderChart8(data) {
  const { dowCounts } = data;
  const dowLabels = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
  chartDayOfWeek = chartUpdate(chartDayOfWeek, "chartDayOfWeek", {
    type: "bar",
    data: {
      labels: dowLabels,
      datasets: [{ label: "Total activity", data: dowCounts, backgroundColor: "rgba(79, 70, 229, 0.7)", borderRadius: 4 }],
    },
    options: {
      ...sharedOptions(dowLabels, "Total PRs"), aspectRatio: 1.5,
      plugins: { ...sharedOptions().plugins, legend: { display: false } },
    },
  });
}

// ── Render charts (progressive) ──────────────────────
function renderCharts() {
  const data = buildTimeSeries();

  // KPI badges (synchronous, cheap)
  const totalMergedPrs = data.mergedPrsDatasets.reduce((sum, ds) => sum + ds.data.reduce((s, v) => s + v, 0), 0);
  $("badgeMergedPrs").textContent   = fmt(totalMergedPrs) + " PRs";
  $("badgeNewContrib").textContent  = fmt(data.newContribData.reduce((s, v) => s + v, 0)) + " new";
  $("badgeTotalContrib").textContent = fmt(data.cumulContribData.at(-1) ?? 0) + " total";
  $("badgeTotalPrs").textContent    = fmt(data.cumulPrsData.at(-1) ?? 0) + " cumul.";

  // Chart 1 (most important — render immediately)
  renderChart1(data);

  // Charts 2-4 (schedule as a batch)
  setTimeout(() => {
    renderChart2(data);
    renderChart3(data);
    renderChart4(data);
  }, 0);

  // Charts 5-8 (second batch)
  setTimeout(() => {
    renderChart5(data);
    renderChart6(data);
    renderChart7(data);
    renderChart8(data);
  }, 50);
}

// ── Network toggle UI ─────────────────────────────────
function resetActiveOrgs() {
  statsState.activeOrgs = new Set(NETWORKS.map((n) => n.id));
}

function bindNetworkToggles() {
  const wrap = $("networkToggles");
  wrap.addEventListener("click", (e) => {
    const btn = e.target.closest("[data-org]");
    if (!btn) return;
    const org = btn.dataset.org;
    if (statsState.activeOrgs.has(org)) {
      statsState.activeOrgs.delete(org);
      if (statsState.activeOrgs.size === 0) resetActiveOrgs();
    } else {
      statsState.activeOrgs.add(org);
    }
    renderNetworkToggles();
    renderCharts();
  });
}

function renderNetworkToggles() {
  const wrap = $("networkToggles");
  wrap.innerHTML = NETWORKS.map((net) => {
    const active = statsState.activeOrgs.has(net.id);
    return `
      <button
        class="net-toggle ${active ? "active" : ""}"
        data-org="${net.id}"
        type="button"
        style="color: ${net.color};"
        aria-pressed="${active}"
      >
        <span class="net-dot" style="background:${net.color};"></span>
        ${net.label}
      </button>`;
  }).join("");
}

// ── Time range buttons ────────────────────────────────
function bindTimeButtons() {
  document.querySelectorAll(".time-btn").forEach((btn) => {
    btn.addEventListener("click", () => {
      document.querySelectorAll(".time-btn").forEach((b) => b.classList.remove("active"));
      btn.classList.add("active");
      statsState.range = btn.dataset.range;
      renderCharts();
    });
  });
}

function bindGranButtons() {
  document.querySelectorAll(".gran-btn").forEach((btn) => {
    btn.addEventListener("click", () => {
      document.querySelectorAll(".gran-btn").forEach((b) => b.classList.remove("active"));
      btn.classList.add("active");
      statsState.gran = btn.dataset.gran;
      renderCharts();
    });
  });
}

// ── Hide bots / ghost toggles ───────────────────────────
function bindHideBotsToggle() {
  const cb = $("hideBotsStats");
  if (!cb) return;
  cb.addEventListener("change", () => {
    statsState.hideBots = cb.checked;
    try {
      localStorage.setItem(HIDE_BOTS_STORAGE_KEY, String(cb.checked));
    } catch (_) { /* ignore */ }
    renderCharts();
  });
}

function bindHideGhostToggle() {
  const cb = $("hideGhostStats");
  if (!cb) return;
  cb.addEventListener("change", () => {
    statsState.hideGhost = cb.checked;
    saveHideGhostPreference(statsState.hideGhost);
    renderCharts();
  });
}

// ── Data loading (from pre-aggregated JSON) ──────────
async function loadAll() {
  const loadState = $("statsLoadState");
  const chartsGrid = $("chartsGrid");
  const loadLabel = $("loadLabel");
  const statusEl = $("dataStatus");

  loadState.removeAttribute("hidden");
  chartsGrid.setAttribute("hidden", "");

  let payload;
  try {
    const res = await fetch(STATS_JSON_URL, { cache: "no-store" });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    payload = await res.json();
  } catch (err) {
    loadLabel.textContent = "";
    if (statusEl) {
      statusEl.innerHTML = `<span class="error">Failed to load stats data: ${err.message}</span>`;
    }
    return;
  }

  // Convert JSON objects to Maps
  const { aggregated_prs, aggregated_prs_ex_bots, users } = payload;
  for (const [org, days] of Object.entries(aggregated_prs)) {
    const m = new Map();
    for (const [k, v] of Object.entries(days)) m.set(k, v);
    statsState.aggregatedPrs.set(org, m);
  }
  for (const [org, days] of Object.entries(aggregated_prs_ex_bots)) {
    const m = new Map();
    for (const [k, v] of Object.entries(days)) m.set(k, v);
    statsState.aggregatedPrsExBots.set(org, m);
  }
  for (const u of users) {
    statsState.userData.set(u.login, {
      firstSeen: new Date(u.first_seen),
      orgs: new Set(u.orgs),
      prCount: u.pr_count,
      isBot: u.is_bot,
      isGhost: u.is_ghost,
    });
  }

  loadLabel.textContent = `${fmt(payload.user_count)} contributors, ${fmt(payload.total_rows)} PRs`;
  loadState.setAttribute("hidden", "");
  chartsGrid.removeAttribute("hidden");

  renderNetworkToggles();
  bindNetworkToggles();
  bindTimeButtons();
  bindGranButtons();
  bindHideBotsToggle();
  bindHideGhostToggle();

  const hb = $("hideBotsStats");
  if (hb) hb.checked = statsState.hideBots;
  const hg = $("hideGhostStats");
  if (hg) hg.checked = statsState.hideGhost;

  renderCharts();

  const observer = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
      if (mutation.attributeName === "class") {
        statsState._memo.hash = null;
        renderCharts();
      }
    });
  });
  observer.observe(document.documentElement, { attributes: true });
}

loadAll().catch((err) => {
  const statusEl = $("dataStatus");
  if (statusEl) {
    statusEl.innerHTML = `<span class="error">${err.message || String(err)}</span>`;
  }
  console.error(err);
});
